<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_font-size-h3</name>
   <tag></tag>
   <elementGuidId>6e14aea4-881f-4a0e-9176-28d1d42c9b96</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;options&quot;)/div[@class=&quot;wrapper dynamicBackground third-bg&quot;]/div[@class=&quot;container-mx small-padding&quot;]/div[@class=&quot;product-category&quot;]/div[@class=&quot;row category-container&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;option-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7 categoryDetails&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4 pull-right text-right&quot;]/div[@class=&quot;font-size-h3&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-size-h3</value>
   </webElementProperties>
</WebElementEntity>
